title: Grassroots Radio Advocates
description: A blog about amateur radio advocacy and education.
baseurl: ""  # Leave as empty string for GitHub Pages
url: "https://your-username.github.io"  # Replace with your GitHub Pages 
URL
theme: minima  # You can change this theme if desired

